-- CREATE TABLE IF NOT EXISTS orders2 (
-- id INTEGER PRIMARY KEY AUTOINCREMENT,
-- client_id INTEGER NOT NULL,
-- orderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
-- orderSum INTEGER NOT NULL
--
-- FOREIGN KEY (client_id) REFERENCES client(id)
-- );

-- status TEXT NOT NULL,
-- total INTEGER CHECK (total >=0) DEFAULT 0

CREATE TABLE IF NOT EXISTS orders2 (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
client_id integer references clients(id),
orderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL  ,
orderSum INTEGER NOT NULL
);
